### ISSUE TITLE
Missing function definition: `get_camera_trajectory_pose`

### ISSUE THREAD

**Issue by longxiang-ai** [hustvl/Dynamic-2DGS#2]
Hello,

Wonderful work! Thank you for making this project available and providing the example scripts. I encountered an issue while running the example command provided in the documentation for rendering a view track:

```
CUDA_VISIBLE_DEVICES=0 python render_mesh_trajectory.py --source_path YOUR/PATH/TO/DATASET/jumpingjacks --model_path outputs/jumpingjacks --deform_type node --hyper_dim 8 --is_blender --eval --local_frame --resolution 1
```

The script includes the following import:

```python
from utils.camera_utils import get_camera_trajectory_pose
```

However, I couldn't locate the definition of the `get_camera_trajectory_pose` function anywhere in the repository.

Could you please confirm if this function is missing, or provide guidance on where I can find it?

Thank you for your help!

Best regards,
Longxiang

**Comment by Shuaizhang7** [comment]
The pose of the rendering trajectory camera is defined in: https://github.com/hustvl/Dynamic-2DGS/blob/72effea81595b36c267688334b192cee9413c9c3/render_mesh_trajectory.py#L200

Therefore, we don’t actually use the get_camera_trajectory_pose function.

If you want to use this function, you can refer to the open source code of DGMesh: https://github.com/Isabella98Liu/DG-Mesh/blob/754f42c67510a65261a878ae447a6280a7dfa6a0/dgmesh/utils/camera_utils.py#L139
