### ISSUE TITLE
A little remind

### ISSUE THREAD

**Issue by xiao10ma** [hustvl/Dynamic-2DGS#4]
Sparse-Controlled Gaussian Splatting
Sparse-Controlled Gaussian Splatting (SC-GS) (Huang et al. 2024b) shows excellent performance in the task of synthesizing novel views in dynamic scenes. It uses sparse control points to control dense 3D Gaussians in the scene. For each control point at timestep $t$, SC-GS uses MLP $\Phi$ to predict a rotation matrix $R_i^t \in \mathbf{S E}(3)$ and rotation matrix $T_i^t \in \mathbb{R}^3$.

for $T_i^t$, it should be translation vector.

**Comment by guanjunwu** [comment]
Thank you! We have found many typos in the paper, we will revise the paper and release the new version (with more experiments) soon^ ^
